Kx integration UI testing
cs4218/cs4218-project-2024-team06 pull request #46
Opened 2024-10-21 20:33 UTC by kohkaixun

2024-10-26 15:16 UTC, Aishwarya-Hariharan-Iyer approved these changes
LGTM!

2024-10-26 15:16 UTC, Aishwarya-Hariharan-Iyer commented on client/src/pages/user/OrdersIntegration.test.js
> +            expect(await screen.findByText(product.description.substring(0, 30))).toBeInTheDocument();
I assume only the first 30 characters are displayed but we can consider ways to make it less implementation-specific perhaps? Just my thoughts! :)

2024-10-26 18:11 UTC, eugenetangkj requested changes
Thanks for the effort! Left some comments for your review. 👍

2024-10-26 18:11 UTC, eugenetangkj commented on .github/workflows/playwright.yml
> +name: Playwright Tests
Do we want this to run? I see the GitHub actions, its not passing. Since we are not graded on this, can I suggest we dont add into GitHub actions?

2024-10-26 18:11 UTC, eugenetangkj commented on .gitignore
> +.env
What is the change made to `.gitignore`?

2024-10-26 18:11 UTC, eugenetangkj commented on client/src/pages/user/OrdersIntegration.test.js
> +        expect(screen.getByText('🛒 Virtual Vault')).toBeInTheDocument();
Wa, this integration test is super long LOL

In my opinion, when u check whether `Header.js` gets rendered, is there a need to check everything of `Header.js`? Or is it sufficient to just check one aspect of `Header.js` to check that it is indeed being rendered? This is because it is very unlikely that a certain part of `Header.js` gets correctly rendered while the other parts do not (unless those parts have some logic associated with them). Instead, the parts that may be affected by the integration are much more valuable to test, instead of just testing every thing.

Just some food for thought, because if we do integration tests for many components next time, we are going to have so many expect statements?

2024-10-26 18:11 UTC, eugenetangkj commented on client/src/pages/user/OrdersIntegration.test.js
> +        const all1Elements = await screen.findAllByText("1");
Why is the name called `all1Elements`? This naming is not too optimal LOL

2024-10-26 18:11 UTC, eugenetangkj commented on client/src/pages/user/OrdersIntegration.test.js
> +        expect(screen.getByText('🛒 Virtual Vault')).toBeInTheDocument();
This is not just applicable to `Header.js`, but also the other UI components that are being integrated.

2024-10-26 18:11 UTC, eugenetangkj commented on e2e/example.spec.js
> +const { test, expect } = require('@playwright/test');
I do not think we need this file anymore? Its just a sample file

2024-10-26 18:11 UTC, eugenetangkj commented on global-playwright-setup.js
> +// process.env.MONGO_URL = process.env.MONGO_URL_TEST;
If this is a comment, there's no need to commit it?

2024-10-27 16:23 UTC, eugenetangkj approved these changes

2024-10-27 16:25 UTC, merged